## 6-е домашнее задание - Библиотека numpy

Банникова Екатерина НПМбд-02-19
 

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [2]:
import numpy as np
np.linspace(-1.3, 2.5, 64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [3]:
a = 10
np.tile([1, 2, 3], a)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [33]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [21]:
x = np.zeros((10,10))
x[:, 0] = 1; x[0, :] = 1; x[:, -1] = 1; x[-1, :] = 1
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [5]:
x = np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [23]:
n = 6
a = np.arange(n**2)
print((a//n+a%n).reshape(n,n))

[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [27]:
Vector1 = np.array([1, 2, 3])
Vector2 = np.array([4, 5, 6])
x = np.dot(Vector1,Vector2)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
y = np.dot(A, B)

C = np.array([ [1, 2], [3, 4], [5, 6] ])
Vector3 = np.array([7, 8])
z = np.dot(C, Vector3)

print('Vector1 x Vector2 =',x)
print('A x B =',y)
print('C x Vector3 =',z)

Vector1 x Vector2 = 32
A x B = [[19 22]
 [43 50]]
C x Vector3 = [23 53 83]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [28]:
x = np.linspace(0,1,21)
y = np.cos(x)
z = np.sin(x)
a = np.vstack((y, z)) 
print('cos=',y)
print('sin=',z)
print(a)

cos= [1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309 0.54030231]
sin= [0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
 0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
 0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
 0.78332691 0.8134155  0.84147098]
[[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
  0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
  0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
  0.62160997 0.58168309 0.54030231]
 [0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
  0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
  0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
  0.78332691 0.8134155  0.84147098]]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [54]:
4 * np.random.rand(3,5) - 1

array([[ 2.53383242, -0.72244862, -0.72010946,  1.18115235,  2.24819789],
       [ 0.16097638,  0.39692096,  2.91763978, -0.8349137 , -0.2118412 ],
       [-0.35473064,  2.36032673,  0.0737153 ,  1.90471226, -0.93547342]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [55]:
a = np.array([[1, 5, 3, 4, 7],[6, 2, 9, 1, 6],[1, 1, 8, 4, 6],[2, 7, 7, 1, 9]])
print('Сумма всех элементов = ',np.sum(a))
print('Сумма элементов в столбцах = ',np.sum(a, axis = 0))
print('Сумма элементов в строках = ',np.sum(a, axis = 1))
print('Среднее значение для каждой строки = ',np.mean(a, axis=1))
print('Дисперсия для каждой строки = ',np.var(a, axis=1))
print('Стандартное отклонение для каждой строки = ', np.sqrt(np.var(a, axis = 1)))

Сумма всех элементов =  90
Сумма элементов в столбцах =  [10 15 27 10 28]
Сумма элементов в строках =  [20 24 20 26]
Среднее значение для каждой строки =  [4.  4.8 4.  5.2]
Дисперсия для каждой строки =  [4.   8.56 7.6  9.76]
Стандартное отклонение для каждой строки =  [2.         2.92574777 2.75680975 3.12409987]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [56]:
x = np.average(a, axis=1)
y = np.sqrt(np.var(a, axis=-1, dtype=float))
print((a - x.reshape(len(x), 1)) / y.reshape(len(y), 1))

[[-1.5         0.5        -0.5         0.          1.5       ]
 [ 0.41015156 -0.9570203   1.43553045 -1.29881326  0.41015156]
 [-1.08821438 -1.08821438  1.4509525   0.          0.72547625]
 [-1.02429504  0.57616596  0.57616596 -1.34438724  1.21635036]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [57]:
A[np.argsort(A[:, 2])]

array([[1, 5, 3, 4, 7],
       [2, 7, 7, 1, 9],
       [1, 1, 8, 4, 6],
       [6, 2, 9, 1, 6]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [58]:
b = a.dot(a.T)
c = a.T.dot(a)
print('B=',b)
print(*b.shape, sep = 'x')
print('C=',c)
print(*c.shape, sep = 'x')

# Матрицы B и C квадратные, но разные по размеру 

B= [[100  89  88 125]
 [ 89 158 120 144]
 [ 88 120 118 123]
 [125 144 123 184]]
4x4
C= [[ 42  32  79  16  67]
 [ 32  79  90  33 116]
 [ 79  90 203  60 186]
 [ 16  33  60  34  67]
 [ 67 116 186  67 202]]
5x5


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [59]:
x = np.trace(b)
y = np.trace(c)
print('Сумма диагональных элементов матриц  𝐵 =', x)
print('Сумма диагональных элементов матриц  C =', y)

Сумма диагональных элементов матриц  𝐵 = 560
Сумма диагональных элементов матриц  C = 560


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [62]:
x = np.linalg.matrix_rank(a)
y = np.linalg.matrix_rank(b)
z = np.linalg.det(b)
print('Ранг матрицы А = ',x,'\nДетерминант и спектр матрицы A посчитать нельзя,т.к. матрица не квадратная ')
print('Ранг матрицы В = ',y,'\nДетерминант матрицы В = ',z)
w, v = np.linalg.eig(b)
f = np.linalg.matrix_rank(c)
e = np.linalg.det(c)
print ("Собственные числа матрицы В = :\n", w)
print ("Собственные векторы матрицы В = :\n", v)
print('Ранг матрицы C = ',f,'\nДетерминант матрицы C = ',e)
w, v = np.linalg.eig(c)
print ("Собственные числа матрицы C = :", w)
print ("Собственные векторы матрицы C = :\n", v)

Ранг матрицы А =  4 
Детерминант и спектр матрицы A посчитать нельзя,т.к. матрица не квадратная 
Ранг матрицы В =  4 
Детерминант матрицы В =  1914525.0000000026
Собственные числа матрицы В = :
 [493.60756852  42.76172197   4.82256505  18.80814446]
Собственные векторы матрицы В = :
 [[-0.40841866 -0.58046459 -0.65925328 -0.24827438]
 [-0.52506372  0.6608595  -0.39371064  0.3640944 ]
 [-0.45683746  0.26775549  0.33995543 -0.77719807]
 [-0.59059446 -0.39323348  0.54296164  0.44917509]]
Ранг матрицы C =  4 
Детерминант матрицы C =  -1.3870190680645495e-10
Собственные числа матрицы C = : [ 4.93607569e+02  4.27617220e+01  1.88081445e+01  4.82256505e+00
 -4.50694223e-15]
Собственные векторы матрицы C = :
 [[-0.23390924 -0.438274    0.47441136 -0.72660008 -0.01373166]
 [-0.34582177  0.62170526  0.42746475  0.02595554 -0.55721636]
 [-0.61842358 -0.54987257 -0.12482198  0.45501087 -0.3042647 ]
 [-0.20599653  0.15035534 -0.75829948 -0.51362612 -0.31004646]
 [-0.63309673  0.31053487 -0.04011378 -

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [70]:
np.random.randint(10)

9

In [63]:
np.random.seed(1032192933)

 $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}=\int\limits_0^2 {(1-\frac{{2}}{{2x + 1}})dx}=\int\limits_0^2 {1dx}-2\int\limits_0^2 {(\frac{{1}}{{2x + 1}})dx}=(t=2x+1)=2-2\int\limits_0^2 {(\frac{{1}}{{2t}})dt}=2-1\int\limits_0^2 {(\frac{{1}}{{t}})dt}=2-ln|4+1|=2-ln5=0.39056$

In [65]:
def f(x):
    return (2 * x - 1) / (2 * x + 1)

def method_rectangle(f, a, b, step):
    x = np.linspace(a, b - step, int((b - a) / step))
    y = f(x) * step
    return np.sum(y)

def method_trapezoid(f, a, b, step):
    x = np.linspace(a, b, int((b - a) / step) + 1)
    y = f(x[0]) + 2 * np.sum(f(x[1:-1])) + f(x[-1])
    return y * step / 2

def method_simpson(f, a, b, step):
    x = np.linspace(a, b, int((b - a) / step) + 1)
    y = f(x[0]) + 4 * np.sum(f(x[1:-1:2])) + 2 * np.sum(f(x[2:-1:2])) + f(x[-1])
    return y * step / 3

print('Метод прямоугольников:', method_rectangle(f, 0, 2, 0.00001))
print('Метод трапеций:', method_trapezoid(f, 0, 2, 0.001))
print('Метод Симпсона:', method_simpson(f, 0, 2, 0.01))

Метод прямоугольников: 0.39055213474369765
Метод трапеций: 0.3905617675660328
Метод Симпсона: 0.3905620822461698
