# Домашняя работа №5


# Банникова Екатерина НПМбд-02-19

# Решение СЛАУ методом LU-разложения и методом LUP-разложения

# 1) Решение СЛАУ методом LU-разложения

LU-разложение  — представление матрицы A в виде произведения двух матриц, A = LU, где L — нижняя треугольная матрица, а U — верхняя треугольная матрица.
LU-разложение используется для решения систем линейных уравнений, обращения матриц и вычисления определителя. LU-разложение существует только в том случае, когда матрица A обратима, а все ведущие (угловые) главные миноры матрицы A невырождены.

In [28]:
import numpy as np

функция LU-разложения матрицы коэффициентов:

In [29]:
def LU_decomposition(A):
    LU = np.array(A, float)
    for k in range(LU.shape[0]-1):
        LU[k+1:, k] /= LU[k, k]
        LU[k+1:, k+1:] -= np.transpose([LU[k+1:, k]]) * LU[k, k+1:]
    return LU

функция получения треугольных матриц L и U из матрицы LU:

In [30]:
def L_and_U(LU):
    L = np.array(LU, float)
    U = np.array(LU, float)
    for i in range(LU.shape[0]):
        L[i, i] = 1
        L[i, i+1:] = 0
        U[i, :i] = 0
    return L, U

функция для решения системы уравнений, исходя из полученного LU-разложения:

In [31]:
def solve_LU(LU, b):
    y = np.array(b, float)
    for i in range(1, len(y)):
        y[i] = b[i] - np.dot(LU[i, :i], y[:i])
    x = np.array(y)
    for i in range(len(y)-1, -1, -1):
        x[i] = (y[i] - np.dot(LU[i, i+1:], x[i+1:])) / LU[i, i]
    return x

функция для решения системы уравнений:


In [32]:
def decompose_to_LU_and_solve(A, b):
    LU = LU_decomposition(A)
    return solve_LU(LU, b)

функция для проверки на равенство двух массивов:

In [33]:
def arrays_equal(a1, a2):
    diff = a1 - a2
    return np.sum(np.abs(diff)) < 1e-10, diff

Делаем LU-разложение матрицы, проверяем, что оно выполнено верно; используя полученное разложение, находим решение СЛАУ и проверяем его. Далее находим решение второй СЛАУ.

In [34]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])

print("Исходная матрица A:\n", A)

LU = LU_decomposition(A)
L, U = L_and_U(LU)

print("LU-разложение:")
print("матрица L:\n", L)
print("матрица U:\n", U)
print("матрица LU:\n", LU)

L_mult_U = np.dot(L, U)

print("Проверка LU-разложения:")
print("произведение матриц L * U:\n", L_mult_U)
arreq, difflu = arrays_equal(L_mult_U, A)
print("проверка: есть ли несовпадение между A и L*U ?\n разница\n", difflu)
print("L*U = A, разложение выполнено правильно" if arreq else "Разложение неверное")

b = np.array([3, 8, 5])
print("Исходный столбец b:\n", b)

x = solve_LU(LU, b)
print("Решение СЛАУ x:\n", x)

print("Проверка решения:")
Ax = np.dot(A, x)
print("Произведение A * x:\n", Ax)
arreq, diffax = arrays_equal(Ax, b)
print("проверка: есть ли несовпадение между A*x и b ?\n разница", diffax)
print("A*x = b, получено правильное решение" if arreq else "Решение неверное")

A2 = np.array([[6.3, -4, 3.7, 8], [9.1, 7, 0, 2.2], [4.75, -3, 5.66, 6], [6, 5, -6.18, 2]])
b2 = np.array([2, 6, 3, 8])
x2 = decompose_to_LU_and_solve(A2, b2)
Ax2 = np.dot(A2, x2)
arreq, diffax2 = arrays_equal(Ax2, b2)
print("\nИсходная матрица A2:\n", A2)
print("Исходный столбец b2:\n", b2)
print("Решение СЛАУ x2:\n", x2)
print("Произведение A2 * x2:\n", Ax2)
print("A2*x2 = b2, получено правильное решение" if arreq else "Решение неверное")


Исходная матрица A:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
LU-разложение:
матрица L:
 [[1. 0. 0.]
 [4. 1. 0.]
 [7. 2. 1.]]
матрица U:
 [[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  1.]]
матрица LU:
 [[ 1.  2.  3.]
 [ 4. -3. -6.]
 [ 7.  2.  1.]]
Проверка LU-разложения:
произведение матриц L * U:
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 10.]]
проверка: есть ли несовпадение между A и L*U ?
 разница
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
L*U = A, разложение выполнено правильно
Исходный столбец b:
 [3 8 5]
Решение СЛАУ x:
 [-7.66666667 17.33333333 -8.        ]
Проверка решения:
Произведение A * x:
 [3. 8. 5.]
проверка: есть ли несовпадение между A*x и b ?
 разница [0. 0. 0.]
A*x = b, получено правильное решение

Исходная матрица A2:
 [[ 6.3  -4.    3.7   8.  ]
 [ 9.1   7.    0.    2.2 ]
 [ 4.75 -3.    5.66  6.  ]
 [ 6.    5.   -6.18  2.  ]]
Исходный столбец b2:
 [2 6 3 8]
Решение СЛАУ x2:
 [-6.92183667  7.04156692  0.57991193  8.95352057]
Произведение A2 * x2:
 [2. 6. 3. 8.]
A2*x2 = b2, получено п

# 2) Решение СЛАУ методом LUP-разложения

LUP-разложение матрицы A - это представление матрицы A в виде произведения PA=LU, где L-нижняя треугольная матрица, U - верхняя треугольная или ступенчатая матрица, P- матрица перестановок (матрица перестановок - эта матрица, полученная из единичной матрицы перестановкой некоторых строк или столбцов).

функция определения матрицы перестановок:

In [35]:
def pivot_matrix(M):
    m = M.shape[0]

    PM = np.zeros([m, m], float)
    for k in range(m):
        PM[k, k] = 1.
    
    print(M)
    for j in range(m):
        row = j
        v = M[j , j]
        for k in range(j + 1, m):
            if M[k , j] > v:
                row = k
                v = M[k , j]
        if j != row:
            PM[[j, row], :] = PM[[row, j], :]

    return PM


функция LUP-разложения матрицы коэффициентов:

In [36]:
def LUP_decomposition(A):
    P = pivot_matrix(A)
    PA = np.dot(P, A)
    LU = LU_decomposition(PA)
    return LU, P

функция для решения системы уравнений, исходя из полученного LUP-разложения:

In [37]:
def solve_LU_P(LU, P, b):
    Pb = np.dot(P, b)
    return solve_LU(LU, Pb)

функция для решения системы уравнений:

In [38]:
def decompose_to_LUP_and_solve(A, b):
    LU, P = LUP_decomposition(A)
    return solve_LU_P(LU, P, b)

Применяем метод LUP-раздожения: находим матрицу перестановок и соответствующее LU-разложение, проверяем, что разложение выполнено верно; используя полученное разложение, находим решение СЛАУ и проверяем его. Далее находим решение второй СЛАУ.

In [39]:
print("Исходная матрица A:\n", A)

LU, P = LUP_decomposition(A)
L, U = L_and_U(LU)

print("LUP-разложение:")
print("матрица P:\n", P)
print("матрица L:\n", L)
print("матрица U:\n", U)
print("матрица LU:\n", LU)

P_mult_A = np.dot(P, A)
L_mult_U = np.dot(L, U)

print("Проверка LUP-разложения:")
print("произведение матриц P * A:\n", P_mult_A)
print("произведение матриц L * U:\n", L_mult_U)
arreq, difflu = arrays_equal(L_mult_U, P_mult_A )
print("проверка: есть ли несовпадение между P*A и L*U ?\n разница\n", difflu)
print("L*U = P*A, разложение выполнено правильно" if arreq else "Разложение неверное")

print("Исходный столбец b:\n", b)

x = solve_LU_P(LU, P, b)
print("Решение СЛАУ x:\n", x)

print("Проверка решения:")
Ax = np.dot(A, x)
print("Произведение A * x:\n", Ax)
arreq, diffax = arrays_equal(Ax, b)
print("проверка: есть ли несовпадение между A*x и b ?\n разница", diffax)
print("A*x = b, получено правильное решение" if arreq else "Решение неверное")

print("\nИсходная матрица A2:\n", A2)
print("Исходный столбец b2:\n", b2)
x2 = decompose_to_LUP_and_solve(A2, b2)
Ax2 = np.dot(A2, x2)
arreq, diffax2 = arrays_equal(Ax2, b2)
print("Решение СЛАУ x2:\n", x2)
print("Произведение A2 * x2:\n", Ax2)
print("A2*x2 = b2, получено правильное решение" if arreq else "Решение неверное")


Исходная матрица A:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
LUP-разложение:
матрица P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
матрица L:
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
матрица U:
 [[ 7.          8.         10.        ]
 [ 0.          0.85714286  1.57142857]
 [ 0.          0.         -0.5       ]]
матрица LU:
 [[ 7.          8.         10.        ]
 [ 0.14285714  0.85714286  1.57142857]
 [ 0.57142857  0.5        -0.5       ]]
Проверка LUP-разложения:
произведение матриц P * A:
 [[ 7.  8. 10.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]]
произведение матриц L * U:
 [[ 7.  8. 10.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]]
проверка: есть ли несовпадение между P*A и L*U ?
 разница
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
L*U = P*A, разложение выполнено правильно
Исходный столбец b:
 [3 8 5]
Решение СЛАУ x:
 [-7.66666667 17.33333333 -8.        ]
Проверка решения:
Произведение A * x:
 [3. 8. 5.]
проверка: ест

# Вывод:

Не всегда можно проводить LU -разложение матрицы. Но LUP- разложение всегда возможно. LU-разложение подходит только для обратимой матрицы A и для невырожденных(угловых) главных миноров матрицы A.